sudo: required
language: go

go:
  - "1.11.x"
  - "1.12.x"  

jobs:
  include:          
    - stage: Release application
      script:
        - GOARCH=amd64 GOOS=linux go build -o tomox-sdk.$TRAVIS_TAG.linux.amd64
        - GOARCH=amd64 GOOS=darwin go build -o tomox-sdk.$TRAVIS_TAG.darwin.amd64
        - GOARCH=amd64 GOOS=windows go build -o tomox-sdk.$TRAVIS_TAG.amd64.exe
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        overwrite: true
        file:
          - proxy.$TRAVIS_TAG.linux.amd64
          - proxy.$TRAVIS_TAG.darwin.amd64
          - proxy.$TRAVIS_TAG.amd64.exe
        on:
          tags: true

stages:
  - name: Release application
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomox-sdk