version: '3'
services:
  # matching-engine:
  #   image: amp-matching-engine
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - AMP_ETHEREUM_NODE_WS_URL=ws://ethereum:8546
  #     - AMP_MONGO_URL=mongodb
  #     - AMP_MONGO_DBNAME
  #     - AMP_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #     - AMP_EXCHANGE_CONTRACT_ADDRESS
  #     - AMP_WETH_CONTRACT_ADDRESS
  #     - AMP_FEE_ACCOUNT_ADDRESS
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  #     - ethereum

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - ./utils/datadir:/data/db
    ports:
      - '27017:27017'

  mongodb-seed:
    image: mongo:latest
    container_name: 'mongodb-seed'
    links:
      - mongodb
    volumes:
      - ./utils/seed-data:/utils/seed-data
    depends_on:
      - mongodb
    command:
      - /bin/sh
      - -c
      - |
        # mongo tomodex --eval "db.dropDatabase()"
        mongoimport --host mongodb --db tomodex --type json --collection tokens --file utils/seed-data/tokens.bson
        mongoimport --host mongodb --db tomodex --type json --collection pairs --file utils/seed-data/pairs.bson
        mongoimport --host mongodb --db tomodex --type json --collection accounts --file utils/seed-data/accounts.bson
        mongoimport --host mongodb --db tomodex --type json --collection wallets --file utils/seed-data/wallets.bson

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
