go get github.com/Sirupsen/logrus
go get github.com/alicebob/miniredis
go get github.com/go-ozzo/ozzo-dbx
go get github.com/go-ozzo/ozzo-routing
go get github.com/gomodule/redigo/redis
go get github.com/op/go-logging
go get github.com/streadway/amqp
go get gopkg.in/mgo.v2
go get github.com/spf13/viper
go get github.com/ethereum/go-ethereum
go get github.com/robfig/cron
go get github.com/go-ozzo/ozzo-validation
go get github.com/gorilla/websocket
go get github.com/spf13/cobra
go get github.com/gorilla/handlers
